### ISSUE TITLE
[CRITICAL] WORKER TIMEOUT errors in stderr (via Stackdriver)

### ISSUE THREAD

**Issue by arsenyspb** [GoogleCloudPlatform/data-science-on-gcp#9] opened 2018-02-21 05:11 UTC
From AppEngine logs - 

```
A  GET 200 86 B 2 ms Chrome 64 / GET 200 86 B 2 ms Chrome 64 
A  INFO: Rejected non-Cron request
 
A  GET 200 236 B 2 ms Chrome 64 /ingest GET 200 236 B 2 ms Chrome 64 
A  INFO: Received cron request true
 
A  INFO: scheduling ingest of year=2016 month=02
 
A  INFO: Requesting data for 2016-02-*
 
A  [2018-02-21 05:04:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:15)
 
A  [2018-02-21 05:04:42 +0000] [15] [INFO] Worker exiting (pid: 15)
 
```

**Comment by lakshmanok** [comment] 2018-03-03 05:54
Looks like the server was being slow ... if the time to download the file exceeds 10 minutes, it causes deadline exceeded errors in app-engine:

https://cloud.google.com/appengine/articles/deadlineexceedederrors

If you run into this problem in your real-world application, you have a couple of alternatives:
(1) change your architecture to use Cloud Functions. Put all the ingest code in a Cloud Function and launch it off in response to the Cron.
(2) reduce the size of the file being downloaded by increasing the frequency of download. For example, instead of downloading monthly files once a month, download weekly files once a week.

**Comment by Canas** [comment] 2018-10-26 14:06
This behavior is caused by gunicorn not by Google. Gunicorn has a 30 second default limit that can be overrided by setting the `--timeout` argument in app.yaml.

Example with 120 seconds timeout:
```
gunicorn -b :$PORT ingestapp:app --timeout 120
```

I was having the same issue with worker timeout error until I did this. Hope it helps!

**Comment by lakshmanok** [comment] 2018-10-26 15:07
Thanks! Do you want to issue a pull request with the above change (so that
you get the attribution), or do you want to me to simply make the change?

**Comment by Canas** [comment] 2018-10-26 18:39
Just did the pull request with the same timeout parameter as my previous post :)

**Comment by lakshmanok** [comment] 2018-10-26 20:44
thanks, Canas.  i don't see any pull request though

**Comment by Canas** [comment] 2018-10-26 22:08
Sorry I was having issues with Google CLA, now it should be ready. Thanks!

**Comment by lakshmanok** [comment] 2018-10-26 23:37
Fixed by Canas in https://github.com/GoogleCloudPlatform/data-science-on-gcp/pull/30

**Closed by lakshmanok** 2018-10-26 23:37 UTC

**Comment by pdoggi** [comment] 2019-06-26 23:40
@Canas Thank you so much! You're a lifesaver.
